version: '3'

services:
  backend:
    build: 
      context: ./server
    container_name: tripbuddy
    ports:
      - "3000:3000"
    healthcheck:
      test: curl --fail http://localhost:3000/healthcheck || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    dns:
      - 8.8.8.8
    

    environment:
      NODE_ENV: production