version: '3'

services:
  backend:
    build: 
      context: .
    container_name: tripbuddy-backend
    command:
      bash -c "npm run test; npm run test-failure"
    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production